module.exports = {
  ACTIONS: {
    HEARTBEAT: 'HEARTBEAT',
    PLAYER_LIST: 'PLAYER_LIST',
    PLAYER_JOIN: 'PLAYER_JOIN',
    PLAYER_QUIT: 'PLAYER_QUIT',
    PLAYER_OFFLINE: 'PLAYER_OFFLINE',
    PLAYER_ERROR: 'PLAYER_ERROR',
    POSITION_FRAMER: 'POSITION_FRAME',
    ATTACK: 'ATTACK',
    GAME_READY: 'GAME_READY',
    GAME_START: 'GAME_START',
    GAME_OVER: 'GAME_OVER',
    PING: 'PING'
  },
  SCENE: {
    INIT: 1000,
    HALL: 1001,
    ROOM: 1002,
    LOADING: 1003,
    GAME: 1004,
    OVER: 1005
  },
  GAME: {
    DURATION: 60,
    FRAMER_DURATION: 120
  }
}