module.exports = {
  ACTIONS: {
    HEARTBEAT: 'HEARTBEAT',
    PLAYER_LIST: 'PLAYER_LIST',
    PLAYER_JOIN: 'PLAYER_JOIN',
    PLAYER_QUIT: 'PLAYER_QUIT',
    PLAYER_OFFLINE: 'PLAYER_OFFLINE',
    PLAYER_ERROR: 'PLAYER_ERROR',
    POSITION_FRAMER: 'POSITION_FRAMER',
    ATTACK: 'ATTACK'
  }
}